---
# tasks file for autoupdate
- name: Update all packages - dnf
  dnf: name=* state=latest
  when: ansible_pkg_mgr == "dnf"
  register: autoupdate_dnf_result

- name: Update all packages - yum
  yum: name=* update_cache=yes state=latest
  when: ansible_pkg_mgr == "yum"
  register: autoupdate_yum_result

- name: Update all packages - apt
  apt: update_cache=yes upgrade=dist autoremove=yes cache_valid_time=300 state=latest
  when: ansible_pkg_mgr == "apt"
  register: autoupdate_apt_result

- name: Check if anything needs autoremoving with apt
  shell: apt-get -y --dry-run autoremove | grep -q "0 to remove" warn=no
  register: check_autoremove
  ignore_errors: True
  changed_when: False
  always_run: True
  when: ansible_pkg_mgr == "apt" and autoupdate_apt_result['changed'] == true

- name: Autoremove unused packages with apt
  command: apt-get -y autoremove warn=no
  when: ansible_pkg_mgr == "apt" and autoupdate_apt_result['changed'] == true and check_autoremove.rc != 0

- name: dnf updates result
  # debug: msg={{ autoupdate_dnf_result['msg'] }}
  debug: var=autoupdate_dnf_result
  when: autoupdate_dnf_result['changed'] == true

- name: yum updates result
  debug: var=autoupdate_yum_result
  # debug: msg={{ autoupdate_yum_result['msg'] }}
  when: autoupdate_yum_result['changed'] == true

- name: apt updates result
  debug: var=autoupdate_apt_result
  # debug: msg={{ autoupdate_apt_result['msg'] }}
  when: autoupdate_apt_result['changed'] == true
